config/routes.rb
Rails.application.routes.draw do
  get 'backups/index'

  get 'home/index'
  get 'home/minor'
  root to: 'home#index'

end

app/models/backup.rb
class Backup < ActiveRecord::Base
  require 'csv'

  def self.import_data
    data = []
    CSV.foreach('public/sample.csv', headers: true) do |row|
      data << {server_name: row['ServerName'], date_time: row['DateTime'], job_name: row['JobName'], event_id: row['EventId'],
        status: row['Status']}
    end
    Backup.create(data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backups_controller.rb
class BackupsController < ApplicationController
  def index
    @backups = Backup.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @mainTitle = "Welcome in Inspinia Rails Seed Project"
    @mainDesc = "It is an application skeleton for a typical Ruby on Rails web app. You can use it to quickly bootstrap your webapp projects and dev/prod environment."
  end

  def minor
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/backups_helper.rb
module BackupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/backups/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>Backups</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/home">Home</a>
            </li>
            <li class="active">
                <strong>Backups</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Backup Status List</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Config option 1</a>
                        </li>
                        <li><a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">

                <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example" id="backup">
                <thead>
                    <tr>
                        <th>Server Name</th>
                        <th>Date & Time</th>
                        <th>Job Name</th>
                        <th>Event ID</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <% @backups.each do |backup| %>
                        <tr>
                            <td><%=  backup.server_name %></td>
                            <td><%=  backup.date_time %></td>
                            <td><%=  backup.job_name %></td>
                            <td><%=  backup.event_id %></td>
                            <td><%=  backup.status %></td>
                          </tr>
                    <% end %>
                </tbody>
            </table>
                </div>

            </div>
        </div>
    </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">

        <div class="col-lg-4">
            <div class="widget navy-bg p-lg text-center">
                <div class="m-b-md">
                    <i class="fa fa-check fa-4x"></i>
                    <h1 class="m-xs">47</h1>
                    <h3 class="font-bold no-margins">
                        Successfull
                    </h3>
                </div><!-- end m-b-md -->
            </div><!-- end widget red-bg p-lg text-center -->
        </div><!-- end col-lg-4 -->

        <div class="col-lg-4">
            <div class="widget yellow-bg p-lg text-center">
                <div class="m-b-md">
                    <i class="fa fa-exclamation fa-4x"></i>
                    <h1 class="m-xs">47</h1>
                    <h3 class="font-bold no-margins">
                        Warning
                    </h3>
                </div><!-- end m-b-md -->
            </div><!-- end widget red-bg p-lg text-center -->
        </div><!-- end col-lg-4 -->

        <div class="col-lg-4">
            <div class="widget red-bg p-lg text-center">
                <div class="m-b-md">
                    <i class="fa fa-times fa-4x"></i>
                    <h1 class="m-xs">47</h1>
                    <h3 class="font-bold no-margins">
                        Notification
                    </h3>
                </div><!-- end m-b-md -->
            </div><!-- end widget red-bg p-lg text-center -->
        </div><!-- end col-lg-4 -->

    </div><!-- end row -->

    <div class="row">
        <div class="text-center">
            <h3>International Sites</h3>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-primary pull-right">Sucess</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">169</h1>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-warning pull-right">Failure</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">188</h1>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-danger pull-right">Failure</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">188</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="text-center">
            <h3>Indonesia Sites</h3>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-primary pull-right">Sucess</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">169</h1>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-warning pull-right">Failure</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">188</h1>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-danger pull-right">Failure</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">188</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="text-center">
            <h3>China Sites</h3>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-primary pull-right">Sucess</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">169</h1>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-warning pull-right">Failure</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">188</h1>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-danger pull-right">Failure</span>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins">188</h1>
                </div>
            </div>
        </div>

    </div><!-- end row -->
</div><!-- end wrapper wrapper-content animated fadeInRight -->

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Operation Dashboard v1.0
    </div>
    <div>
        <strong>Copyright</strong> Averis &copy; 2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Azren</strong>
                        </span> <span class="text-muted text-xs block">Tech Support<b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="mailbox.html">Mailbox</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/" do %>
                <i class="fa fa-home"></i> <span class="nav-label">Home</span>
                <% end %>
            </li>
            <li class="<%= 'active' if current_page?('#') %>">
                <%= link_to root_path do %>
                <i class="fa fa-archive"></i> <span class="nav-label">Backups Summary</span>
                <% end %>
                <%= link_to backups_index_path do %>
                <i class="fa fa-archive"></i> <span class="nav-label">Backups List</span>
                <% end %>
            </li>
        </ul>

    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>

        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="#">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ops Dashboard</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

</body>
</html>